print("Назовите все этапы развития человека (всего 5)")
a1 = input("Укажите самый древний - ")
a2 = input("Укажите следующий - ")
a3 = input("За ним следует - ")
a4 = input("Следующий - ")
a5 = input("Завершающий этап - ")
print("Ваш ответ:")
print(a1, a2, a3, a4, a5, sep='=>')
print("Правильный ответ:")
print("Australopithecus africanus => Homo habilis => Homo erectus => Homo Neanderthalensis => Homo Sapiens Sapiens.")
input('Нажмите ENTER чтобы выйти')
